name: "Hue thief addon"
description: "Run hue thief to unpair lights"
version: "1.0.16"
slug: "hue-thief"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - config:rw
options:
  device: /dev/ttyAMA1
  baud_rate: 115200
schema:
  device: str?
  baud_rate: int?
usb: true
uart: true
ports:
  8000/tcp: 8000
