name: "Hue thief addon"
description: "Run hue thief to unpair lights"
version: "1.0.65"
slug: "hue-thief"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
# map:
  # - config:rw
options:
  device: /dev/ttyAMA1
  baud_rate: 115200
  run_main: server
schema:
  device: str?
  baud_rate: int?
  run_main: str?
usb: true
uart: true
ports:
  8099/tcp: 8099
ingress: true
