name: "Hue thief addon"
description: "Run hue thief to unpair lights"
version: "1.0.6"
slug: "hue-thief"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
devices:
  - /dev/ttyAMA1
