name: "Hue thief addon"
description: "Run hue thief to unpair lights"
version: "1.0.9"
slug: "hue-thief"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  device: /dev/ttyAMA1
  baud_rate: 115200
schema: false
